import type { Metadata } from "next";

import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "sonner";
const outfit = localFont({
  src: [
    {
      path: "../public/font/Outfit-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/font/Outfit-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/font/Outfit-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "NovaCrust-Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} antialiased`}>
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
